"""phase 2 initial tenant menu and order schema

Revision ID: 20260716_0001
Revises: 
Create Date: 2026-07-16 01:20:02.516474
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260716_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('default_locale', sa.String(length=32), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_simulation', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('ACTIVE','INACTIVE')", name=op.f('ck_restaurants_status_valid')),
    sa.CheckConstraint('length(currency) = 3', name=op.f('ck_restaurants_currency_iso3')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restaurants')),
    sa.UniqueConstraint('code', name=op.f('uq_restaurants_code'))
    )
    op.create_index('ix_restaurants_status_simulation', 'restaurants', ['status', 'is_simulation'], unique=False)
    op.create_table('allergens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_allergens_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_allergens')),
    sa.UniqueConstraint('restaurant_id', 'code', name='uq_allergens_restaurant_code')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('external_reference', sa.String(length=160), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_customers_restaurant_id_restaurants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('restaurant_id', 'external_reference', name='uq_customers_restaurant_external')
    )
    op.create_index('ix_customers_restaurant_synthetic', 'customers', ['restaurant_id', 'is_synthetic'], unique=False)
    op.create_table('menu_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('DRAFT','PUBLISHED','ARCHIVED')", name=op.f('ck_menu_versions_status_valid')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_menu_versions_version_positive')),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_menu_versions_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_versions')),
    sa.UniqueConstraint('id', 'restaurant_id', name='uq_menu_versions_id_restaurant'),
    sa.UniqueConstraint('restaurant_id', 'version_number', name='uq_menu_versions_restaurant_number')
    )
    op.create_index('ix_menu_versions_restaurant_status', 'menu_versions', ['restaurant_id', 'status'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('active_menu_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('ACTIVE','INACTIVE')", name=op.f('ck_branches_status_valid')),
    sa.ForeignKeyConstraint(['active_menu_version_id', 'restaurant_id'], ['menu_versions.id', 'menu_versions.restaurant_id'], name='fk_branches_active_menu_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_branches_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches')),
    sa.UniqueConstraint('id', 'restaurant_id', name='uq_branches_id_restaurant'),
    sa.UniqueConstraint('restaurant_id', 'code', name='uq_branches_restaurant_code')
    )
    op.create_index('ix_branches_active_menu', 'branches', ['restaurant_id', 'active_menu_version_id'], unique=False)
    op.create_index('ix_branches_restaurant_status', 'branches', ['restaurant_id', 'status'], unique=False)
    op.create_table('menu_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_version_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['menu_version_id'], ['menu_versions.id'], name=op.f('fk_menu_categories_menu_version_id_menu_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_categories')),
    sa.UniqueConstraint('id', 'menu_version_id', name='uq_menu_categories_id_version'),
    sa.UniqueConstraint('menu_version_id', 'code', name='uq_menu_categories_version_code')
    )
    op.create_index('ix_menu_categories_version_sort', 'menu_categories', ['menu_version_id', 'sort_order'], unique=False)
    op.create_table('modifier_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_version_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('min_selections', sa.Integer(), nullable=False),
    sa.Column('max_selections', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('max_selections >= min_selections', name=op.f('ck_modifier_groups_max_gte_min')),
    sa.CheckConstraint('min_selections >= 0', name=op.f('ck_modifier_groups_min_nonnegative')),
    sa.ForeignKeyConstraint(['menu_version_id'], ['menu_versions.id'], name=op.f('fk_modifier_groups_menu_version_id_menu_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modifier_groups')),
    sa.UniqueConstraint('menu_version_id', 'code', name='uq_modifier_groups_version_code')
    )
    op.create_table('conversation_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_key', sa.String(length=160), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=32), nullable=False),
    sa.Column('state_json', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('ACTIVE','CLOSED')", name=op.f('ck_conversation_sessions_status_valid')),
    sa.CheckConstraint('version > 0', name=op.f('ck_conversation_sessions_version_positive')),
    sa.ForeignKeyConstraint(['branch_id', 'restaurant_id'], ['branches.id', 'branches.restaurant_id'], name='fk_sessions_branch_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_conversation_sessions_restaurant_id_restaurants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_sessions')),
    sa.UniqueConstraint('id', 'restaurant_id', 'branch_id', name='uq_sessions_id_tenant'),
    sa.UniqueConstraint('restaurant_id', 'branch_id', 'session_key', name='uq_sessions_tenant_key')
    )
    op.create_index('ix_sessions_key', 'conversation_sessions', ['session_key'], unique=False)
    op.create_index('ix_sessions_tenant_status', 'conversation_sessions', ['restaurant_id', 'branch_id', 'status'], unique=False)
    op.create_table('delivery_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('fee_minor', sa.Integer(), nullable=False),
    sa.Column('minimum_order_minor', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.CheckConstraint('fee_minor >= 0', name=op.f('ck_delivery_zones_fee_nonnegative')),
    sa.CheckConstraint('minimum_order_minor >= 0', name=op.f('ck_delivery_zones_minimum_nonnegative')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_delivery_zones_branch_id_branches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_zones')),
    sa.UniqueConstraint('branch_id', 'code', name='uq_delivery_zones_branch_code')
    )
    op.create_index('ix_delivery_zones_branch_active', 'delivery_zones', ['branch_id', 'active'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_idempotency_records_branch_id_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_idempotency_records_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_records')),
    sa.UniqueConstraint('restaurant_id', 'branch_id', 'scope', 'idempotency_key', name='uq_idempotency_tenant_scope_key')
    )
    op.create_index('ix_idempotency_expiry', 'idempotency_records', ['expires_at'], unique=False)
    op.create_index('ix_idempotency_resource', 'idempotency_records', ['resource_type', 'resource_id'], unique=False)
    op.create_table('menu_category_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['menu_categories.id'], name=op.f('fk_menu_category_translations_category_id_menu_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_category_translations')),
    sa.UniqueConstraint('category_id', 'locale', name='uq_category_translations_locale')
    )
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_version_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('base_price_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('attributes_json', sa.JSON(), nullable=False),
    sa.CheckConstraint('base_price_minor >= 0', name=op.f('ck_menu_items_price_nonnegative')),
    sa.CheckConstraint('length(currency) = 3', name=op.f('ck_menu_items_currency_iso3')),
    sa.ForeignKeyConstraint(['category_id', 'menu_version_id'], ['menu_categories.id', 'menu_categories.menu_version_id'], name='fk_menu_items_category_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['menu_version_id'], ['menu_versions.id'], name=op.f('fk_menu_items_menu_version_id_menu_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_items')),
    sa.UniqueConstraint('id', 'menu_version_id', name='uq_menu_items_id_version'),
    sa.UniqueConstraint('menu_version_id', 'code', name='uq_menu_items_version_code')
    )
    op.create_index('ix_menu_items_version_active', 'menu_items', ['menu_version_id', 'active'], unique=False)
    op.create_index('ix_menu_items_version_category', 'menu_items', ['menu_version_id', 'category_id'], unique=False)
    op.create_table('modifier_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modifier_group_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('price_delta_minor', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('price_delta_minor >= 0', name=op.f('ck_modifier_options_price_delta_nonnegative')),
    sa.ForeignKeyConstraint(['modifier_group_id'], ['modifier_groups.id'], name=op.f('fk_modifier_options_modifier_group_id_modifier_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modifier_options')),
    sa.UniqueConstraint('modifier_group_id', 'code', name='uq_modifier_options_group_code')
    )
    op.create_table('opening_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('reason_code', sa.String(length=80), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.CheckConstraint('weekday >= 0 and weekday <= 6', name=op.f('ck_opening_hours_weekday_range')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_opening_hours_branch_id_branches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opening_hours')),
    sa.UniqueConstraint('branch_id', 'weekday', 'start_time', 'end_time', 'effective_date', name='uq_opening_hours_slot')
    )
    op.create_index('ix_opening_hours_branch_weekday', 'opening_hours', ['branch_id', 'weekday'], unique=False)
    op.create_table('branch_item_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('sold_out_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason_code', sa.String(length=80), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_branch_item_availability_branch_id_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('fk_branch_item_availability_menu_item_id_menu_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branch_item_availability')),
    sa.UniqueConstraint('branch_id', 'menu_item_id', name='uq_branch_item_availability_pair')
    )
    op.create_index('ix_branch_item_availability_lookup', 'branch_item_availability', ['branch_id', 'menu_item_id', 'available'], unique=False)
    op.create_table('menu_item_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('menu_version_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=32), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('normalized_alias', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id', 'menu_version_id'], ['menu_items.id', 'menu_items.menu_version_id'], name='fk_item_aliases_item_version', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_version_id'], ['menu_versions.id'], name=op.f('fk_menu_item_aliases_menu_version_id_menu_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_item_aliases')),
    sa.UniqueConstraint('menu_version_id', 'locale', 'normalized_alias', name='uq_item_aliases_version_locale_norm')
    )
    op.create_index('ix_item_aliases_lookup', 'menu_item_aliases', ['menu_version_id', 'locale', 'normalized_alias'], unique=False)
    op.create_table('menu_item_allergens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('allergen_id', sa.Integer(), nullable=False),
    sa.Column('declaration', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('menu_version_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("declaration in ('CONTAINS','MAY_CONTAIN','UNKNOWN')", name=op.f('ck_menu_item_allergens_declaration_valid')),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens.id'], name=op.f('fk_menu_item_allergens_allergen_id_allergens'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['menu_item_id', 'menu_version_id'], ['menu_items.id', 'menu_items.menu_version_id'], name='fk_item_allergens_item_version', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_version_id'], ['menu_versions.id'], name=op.f('fk_menu_item_allergens_menu_version_id_menu_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_item_allergens')),
    sa.UniqueConstraint('menu_item_id', 'allergen_id', name='uq_item_allergens_pair')
    )
    op.create_index('ix_item_allergens_version', 'menu_item_allergens', ['menu_version_id', 'menu_item_id'], unique=False)
    op.create_table('menu_item_modifier_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('modifier_group_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('fk_menu_item_modifier_groups_menu_item_id_menu_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modifier_group_id'], ['modifier_groups.id'], name=op.f('fk_menu_item_modifier_groups_modifier_group_id_modifier_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_item_modifier_groups')),
    sa.UniqueConstraint('menu_item_id', 'modifier_group_id', name='uq_item_modifier_group_pair')
    )
    op.create_table('menu_item_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('fk_menu_item_translations_menu_item_id_menu_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_item_translations')),
    sa.UniqueConstraint('menu_item_id', 'locale', name='uq_item_translations_locale')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=64), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('draft_version', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal_minor', sa.Integer(), nullable=False),
    sa.Column('delivery_fee_minor', sa.Integer(), nullable=False),
    sa.Column('total_minor', sa.Integer(), nullable=False),
    sa.Column('fulfillment_type', sa.String(length=24), nullable=False),
    sa.Column('delivery_zone_id', sa.Integer(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("fulfillment_type in ('delivery','pickup')", name=op.f('ck_orders_fulfillment_valid')),
    sa.CheckConstraint("status in ('DRAFT','CUSTOMER_CONFIRMED','SUBMISSION_STARTED','MERCHANT_PENDING','MERCHANT_ACCEPTED','MERCHANT_REJECTED','SUBMISSION_FAILED','CANCELLED','COMPLETED')", name=op.f('ck_orders_status_valid')),
    sa.CheckConstraint('delivery_fee_minor >= 0', name=op.f('ck_orders_delivery_fee_nonnegative')),
    sa.CheckConstraint('draft_version > 0', name=op.f('ck_orders_draft_version_positive')),
    sa.CheckConstraint('length(currency) = 3', name=op.f('ck_orders_currency_iso3')),
    sa.CheckConstraint('subtotal_minor >= 0', name=op.f('ck_orders_subtotal_nonnegative')),
    sa.CheckConstraint('total_minor = subtotal_minor + delivery_fee_minor', name=op.f('ck_orders_total_matches')),
    sa.ForeignKeyConstraint(['branch_id', 'restaurant_id'], ['branches.id', 'branches.restaurant_id'], name='fk_orders_branch_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_orders_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['delivery_zone_id'], ['delivery_zones.id'], name=op.f('fk_orders_delivery_zone_id_delivery_zones'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_orders_restaurant_id_restaurants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id', 'restaurant_id', 'branch_id'], ['conversation_sessions.id', 'conversation_sessions.restaurant_id', 'conversation_sessions.branch_id'], name='fk_orders_session_tenant', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('public_id', name='uq_orders_public_id')
    )
    op.create_index('ix_orders_session_created', 'orders', ['session_id', 'created_at'], unique=False)
    op.create_index('ix_orders_tenant_status', 'orders', ['restaurant_id', 'branch_id', 'status'], unique=False)
    op.create_table('order_confirmations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('draft_version', sa.Integer(), nullable=False),
    sa.Column('confirmation_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_confirmations_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_confirmations')),
    sa.UniqueConstraint('confirmation_fingerprint', name='uq_confirmations_fingerprint'),
    sa.UniqueConstraint('order_id', 'draft_version', name='uq_confirmations_order_version')
    )
    op.create_table('order_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.CheckConstraint('sequence_number > 0', name=op.f('ck_order_events_sequence_positive')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_events_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_events')),
    sa.UniqueConstraint('order_id', 'sequence_number', name='uq_order_events_sequence')
    )
    op.create_index('ix_order_events_order_occurred', 'order_events', ['order_id', 'occurred_at'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('menu_version_id', sa.Integer(), nullable=False),
    sa.Column('item_code_snapshot', sa.String(length=100), nullable=False),
    sa.Column('item_name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('unit_price_minor', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('modifier_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('allergen_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('line_total_minor', sa.Integer(), nullable=False),
    sa.CheckConstraint('line_total_minor = unit_price_minor * quantity', name=op.f('ck_order_items_line_total_matches')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_items_quantity_positive')),
    sa.CheckConstraint('unit_price_minor >= 0', name=op.f('ck_order_items_unit_price_nonnegative')),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('fk_order_items_menu_item_id_menu_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['menu_version_id'], ['menu_versions.id'], name=op.f('fk_order_items_menu_version_id_menu_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index('ix_order_items_order', 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_items_order', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_order_events_order_occurred', table_name='order_events')
    op.drop_table('order_events')
    op.drop_table('order_confirmations')
    op.drop_index('ix_orders_tenant_status', table_name='orders')
    op.drop_index('ix_orders_session_created', table_name='orders')
    op.drop_table('orders')
    op.drop_table('menu_item_translations')
    op.drop_table('menu_item_modifier_groups')
    op.drop_index('ix_item_allergens_version', table_name='menu_item_allergens')
    op.drop_table('menu_item_allergens')
    op.drop_index('ix_item_aliases_lookup', table_name='menu_item_aliases')
    op.drop_table('menu_item_aliases')
    op.drop_index('ix_branch_item_availability_lookup', table_name='branch_item_availability')
    op.drop_table('branch_item_availability')
    op.drop_index('ix_opening_hours_branch_weekday', table_name='opening_hours')
    op.drop_table('opening_hours')
    op.drop_table('modifier_options')
    op.drop_index('ix_menu_items_version_category', table_name='menu_items')
    op.drop_index('ix_menu_items_version_active', table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_table('menu_category_translations')
    op.drop_index('ix_idempotency_resource', table_name='idempotency_records')
    op.drop_index('ix_idempotency_expiry', table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index('ix_delivery_zones_branch_active', table_name='delivery_zones')
    op.drop_table('delivery_zones')
    op.drop_index('ix_sessions_tenant_status', table_name='conversation_sessions')
    op.drop_index('ix_sessions_key', table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    op.drop_table('modifier_groups')
    op.drop_index('ix_menu_categories_version_sort', table_name='menu_categories')
    op.drop_table('menu_categories')
    op.drop_index('ix_branches_restaurant_status', table_name='branches')
    op.drop_index('ix_branches_active_menu', table_name='branches')
    op.drop_table('branches')
    op.drop_index('ix_menu_versions_restaurant_status', table_name='menu_versions')
    op.drop_table('menu_versions')
    op.drop_index('ix_customers_restaurant_synthetic', table_name='customers')
    op.drop_table('customers')
    op.drop_table('allergens')
    op.drop_index('ix_restaurants_status_simulation', table_name='restaurants')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
