from __future__ import annotations

from enum import StrEnum


class RestaurantStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class BranchStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class MenuVersionStatus(StrEnum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    ARCHIVED = "ARCHIVED"


class AllergenDeclaration(StrEnum):
    CONTAINS = "CONTAINS"
    MAY_CONTAIN = "MAY_CONTAIN"
    UNKNOWN = "UNKNOWN"


class SessionStatus(StrEnum):
    ACTIVE = "ACTIVE"
    CLOSED = "CLOSED"


class OrderStatus(StrEnum):
    DRAFT = "DRAFT"
    CUSTOMER_CONFIRMED = "CUSTOMER_CONFIRMED"
    SUBMISSION_STARTED = "SUBMISSION_STARTED"
    MERCHANT_PENDING = "MERCHANT_PENDING"
    MERCHANT_ACCEPTED = "MERCHANT_ACCEPTED"
    MERCHANT_REJECTED = "MERCHANT_REJECTED"
    SUBMISSION_FAILED = "SUBMISSION_FAILED"
    CANCELLED = "CANCELLED"
    COMPLETED = "COMPLETED"


class MerchantStatus(StrEnum):
    NOT_INTEGRATED = "NOT_INTEGRATED"
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    UNKNOWN = "UNKNOWN"


class ActorType(StrEnum):
    CUSTOMER = "CUSTOMER"
    SYSTEM = "SYSTEM"
    MERCHANT_FIXTURE = "MERCHANT_FIXTURE"
    OPERATOR = "OPERATOR"


class DecisionClass(StrEnum):
    AUTO_DRAFT = "AUTO_DRAFT"
    CONFIRM = "CONFIRM"
    HANDOFF = "HANDOFF"
    REFUSE = "REFUSE"


class HandoffReasonCode(StrEnum):
    EXPLICIT_HUMAN_REQUEST = "EXPLICIT_HUMAN_REQUEST"
    SEVERE_ALLERGY = "SEVERE_ALLERGY"
    CROSS_CONTAMINATION = "CROSS_CONTAMINATION"
    REPEATED_MISUNDERSTANDING = "REPEATED_MISUNDERSTANDING"
    AMBIGUOUS_ITEM = "AMBIGUOUS_ITEM"
    AMBIGUOUS_QUANTITY = "AMBIGUOUS_QUANTITY"
    UNVERIFIED_ADDRESS = "UNVERIFIED_ADDRESS"
    PRICE_UNAVAILABLE = "PRICE_UNAVAILABLE"
    MENU_DATA_MISSING = "MENU_DATA_MISSING"
    COMPLAINT = "COMPLAINT"
    REFUND_REQUEST = "REFUND_REQUEST"
    PAYMENT_DISPUTE = "PAYMENT_DISPUTE"
    MERCHANT_REJECTED = "MERCHANT_REJECTED"
    MERCHANT_TIMEOUT = "MERCHANT_TIMEOUT"
    SYSTEM_FAILURE = "SYSTEM_FAILURE"
    LANGUAGE_UNSUPPORTED = "LANGUAGE_UNSUPPORTED"
    ABUSE_OR_SECURITY = "ABUSE_OR_SECURITY"
    REGULATED_ITEM = "REGULATED_ITEM"


class RefusalReasonCode(StrEnum):
    CROSS_TENANT_ACCESS = "CROSS_TENANT_ACCESS"
    UNAUTHORIZED_ORDER_ACCESS = "UNAUTHORIZED_ORDER_ACCESS"
    FORGE_MERCHANT_ACCEPTANCE = "FORGE_MERCHANT_ACCEPTANCE"
    BYPASS_CONFIRMATION = "BYPASS_CONFIRMATION"
    CARD_DATA_STORAGE = "CARD_DATA_STORAGE"
    UNSUPPORTED_SAFETY_GUARANTEE = "UNSUPPORTED_SAFETY_GUARANTEE"
    INTERNAL_SECRET_EXTRACTION = "INTERNAL_SECRET_EXTRACTION"
    SECURITY_ATTACK = "SECURITY_ATTACK"


class HandoffStatus(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    REQUESTED = "REQUESTED"
    PENDING = "PENDING"
    SIMULATED_AGENT_ASSIGNED = "SIMULATED_AGENT_ASSIGNED"
    SIMULATED_AGENT_CONNECTED = "SIMULATED_AGENT_CONNECTED"
    RESOLVED = "RESOLVED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class HandoffFailureCode(StrEnum):
    NO_AGENT_AVAILABLE = "NO_AGENT_AVAILABLE"
    QUEUE_TIMEOUT = "QUEUE_TIMEOUT"
    ASSIGNMENT_FAILED = "ASSIGNMENT_FAILED"
    CONNECTION_FAILED = "CONNECTION_FAILED"
    CASE_CANCELLED = "CASE_CANCELLED"
    SYSTEM_ERROR = "SYSTEM_ERROR"


class HandoffActorType(StrEnum):
    CUSTOMER = "CUSTOMER"
    ORCHESTRATOR = "ORCHESTRATOR"
    SIMULATION_PROVIDER = "SIMULATION_PROVIDER"
    SYSTEM = "SYSTEM"
