param(
  [switch]$RefreshDevLock,
  [switch]$BootstrapDevLock,
  [switch]$Verify
)

$ErrorActionPreference = "Stop"
$PSNativeCommandUseErrorActionPreference = $true

$ProjectRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$BackendPython = Join-Path $ProjectRoot "backend\.venv\Scripts\python.exe"
$PinnedPython = "3.13.2"
$PinnedPip = "26.1.2"
$BootstrapPipTools = "7.5.3"
$ProductionInputRelative = "backend\requirements.txt"
$ProductionLockRelative = "backend\requirements.lock.txt"
$DevInputRelative = "backend\requirements-dev.in"
$DevLockRelative = "backend\requirements-dev.lock.txt"
$ProductionInput = Join-Path $ProjectRoot $ProductionInputRelative
$DevInput = Join-Path $ProjectRoot $DevInputRelative
$DevLock = Join-Path $ProjectRoot $DevLockRelative

function Invoke-CheckedPython {
  param(
    [Parameter(Mandatory = $true)][string]$Python,
    [Parameter(ValueFromRemainingArguments = $true)][string[]]$Arguments
  )

  & $Python @Arguments | Out-Host
  if ($LASTEXITCODE -ne 0) {
    throw "Python command failed with exit code ${LASTEXITCODE}: $Python $($Arguments -join ' ')"
  }
}

function Assert-LockFileSafe {
  param([Parameter(Mandatory = $true)][string]$Path)

  $Forbidden = Select-String -LiteralPath $Path -Pattern @(
    'file:///',
    '@\s+file:',
    '[A-Za-z]:[\\/]',
    '--index-url',
    '--extra-index-url',
    '--find-links',
    '--trusted-host',
    '^\s*(?:-e|--editable)(?:\s|=)',
    '@\s+https?://'
  )
  if ($Forbidden) {
    throw "Lock file contains a forbidden path, package source, index, or editable install: $Path"
  }

  if (-not (Select-String -LiteralPath $Path -Pattern '--hash=sha256:' -Quiet)) {
    throw "Lock file does not contain hashes: $Path"
  }
}

function Normalize-LockHeader {
  param(
    [Parameter(Mandatory = $true)][string]$Path,
    [Parameter(Mandatory = $true)][string]$RegenerateCommand,
    [Parameter(Mandatory = $true)][string]$PipToolsVersion,
    [Parameter(Mandatory = $true)][string]$PythonVersion
  )

  $Content = Get-Content -Raw -Encoding UTF8 -LiteralPath $Path
  $GeneratedHeader = '(?s)\A#\r?\n# This file is autogenerated by pip-compile with Python [^\r\n]+\r?\n# by the following command:\r?\n#\r?\n#\s+[^\r\n]+\r?\n#\r?\n'
  $StableHeader = @"
#
# This file is autogenerated by pip-compile $PipToolsVersion with Python $PythonVersion.
# Do not edit this file by hand.
# Regenerate it from the repository root with:
#
#    $RegenerateCommand
#
"@
  $StableHeader += [Environment]::NewLine
  $Normalized = [Regex]::Replace($Content, $GeneratedHeader, $StableHeader, 1)
  if ($Normalized -eq $Content) {
    throw "Unexpected pip-compile header; lock file was not normalized: $Path"
  }

  # pip-compile resolves transitive dependencies for the host platform and does
  # not carry pyttsx3's Windows marker onto its Windows-only dependency closure.
  # Keep one hashed production lock installable by both CI operating systems.
  foreach ($Package in @("comtypes", "pypiwin32", "pywin32")) {
    $Pattern = "(?m)^($([Regex]::Escape($Package))==[^\s;]+)(\s+\\)\r?$"
    $Normalized = [Regex]::Replace(
      $Normalized,
      $Pattern,
      '$1 ; platform_system == "Windows"$2'
    )
  }

  [IO.File]::WriteAllText($Path, $Normalized, [Text.UTF8Encoding]::new($false))
  Assert-LockFileSafe -Path $Path
}

function New-ToolingEnvironment {
  param(
    [Parameter(Mandatory = $true)][string]$Path,
    [switch]$Bootstrap
  )

  Invoke-CheckedPython -Python $BackendPython -Arguments @("-m", "venv", $Path)
  $ToolingPython = Join-Path $Path "Scripts\python.exe"
  Invoke-CheckedPython -Python $ToolingPython -Arguments @("-m", "pip", "install", "pip==$PinnedPip")
  if ($Bootstrap) {
    Write-Host "Bootstrapping the first development lock with pip-tools==$BootstrapPipTools." -ForegroundColor Yellow
    Invoke-CheckedPython -Python $ToolingPython -Arguments @("-m", "pip", "install", "pip-tools==$BootstrapPipTools")
  } else {
    Invoke-CheckedPython -Python $ToolingPython -Arguments @("-m", "pip", "install", "-r", $DevLock)
  }
  return $ToolingPython
}

function Compile-Lock {
  param(
    [Parameter(Mandatory = $true)][string]$Python,
    [Parameter(Mandatory = $true)][string]$InputRelative,
    [Parameter(Mandatory = $true)][string]$OutputRelative,
    [Parameter(Mandatory = $true)][string]$RegenerateCommand
  )

  $env:CUSTOM_COMPILE_COMMAND = $RegenerateCommand
  Push-Location $ProjectRoot
  try {
    Invoke-CheckedPython -Python $Python -Arguments @(
      "-m", "piptools", "compile",
      $InputRelative,
      "--output-file", $OutputRelative,
      "--generate-hashes",
      "--allow-unsafe",
      "--strip-extras",
      "--quiet"
    )
  } finally {
    Pop-Location
  }

  $OutputPath = Join-Path $ProjectRoot $OutputRelative
  $ActualPython = (& $Python -c "import platform; print(platform.python_version())").Trim()
  $PipToolsVersion = (& $Python -c "import importlib.metadata; print(importlib.metadata.version('pip-tools'))").Trim()
  Normalize-LockHeader `
    -Path $OutputPath `
    -RegenerateCommand $RegenerateCommand `
    -PipToolsVersion $PipToolsVersion `
    -PythonVersion $ActualPython
  $PackageCount = (Select-String -LiteralPath $OutputPath -Pattern '^[A-Za-z0-9_.-]+==').Count
  Write-Host "Generated $OutputPath with $PackageCount pinned packages and hashes." -ForegroundColor Green
}

if (-not (Test-Path -LiteralPath $BackendPython -PathType Leaf)) {
  throw "Backend virtual environment not found: $BackendPython"
}
if ($BootstrapDevLock -and -not $RefreshDevLock) {
  throw "-BootstrapDevLock requires -RefreshDevLock."
}
foreach ($RequiredPath in @($ProductionInput, $DevInput)) {
  if (-not (Test-Path -LiteralPath $RequiredPath -PathType Leaf)) {
    throw "Required dependency input not found: $RequiredPath"
  }
}

$ConfiguredPython = (Get-Content -Raw -LiteralPath (Join-Path $ProjectRoot ".python-version")).Trim()
if ($ConfiguredPython -ne $PinnedPython) {
  throw ".python-version must remain $PinnedPython; found $ConfiguredPython."
}
$ActualPython = (& $BackendPython -c "import platform; print(platform.python_version())").Trim()
if ($ActualPython -ne $PinnedPython) {
  throw "Lock generation requires Python $PinnedPython; found $ActualPython."
}

$ProductionInputHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $ProductionInput).Hash
$TempBase = if ($env:LOCALAPPDATA) { Join-Path $env:LOCALAPPDATA "Temp" } else { [IO.Path]::GetTempPath() }
$TempRoot = Join-Path $TempBase ("order-agent-lock-tools-{0}" -f [Guid]::NewGuid().ToString("N"))
$ToolingVenv = Join-Path $TempRoot "tooling-venv"

try {
  New-Item -ItemType Directory -Path $TempRoot -Force | Out-Null
  $Bootstrap = $BootstrapDevLock -or -not (Test-Path -LiteralPath $DevLock -PathType Leaf)
  $ToolingPython = New-ToolingEnvironment -Path $ToolingVenv -Bootstrap:$Bootstrap

  if ($RefreshDevLock) {
    Compile-Lock `
      -Python $ToolingPython `
      -InputRelative $DevInputRelative `
      -OutputRelative $DevLockRelative `
      -RegenerateCommand ".\scripts\compile_backend_lock.ps1 -RefreshDevLock"

    Remove-Item -LiteralPath $ToolingVenv -Recurse -Force
    $ToolingPython = New-ToolingEnvironment -Path $ToolingVenv
  } elseif ($Bootstrap) {
    throw "Development lock is missing. Run .\scripts\compile_backend_lock.ps1 -RefreshDevLock to bootstrap it."
  }

  Compile-Lock `
    -Python $ToolingPython `
    -InputRelative $ProductionInputRelative `
    -OutputRelative $ProductionLockRelative `
    -RegenerateCommand ".\scripts\compile_backend_lock.ps1"

  if ($Verify) {
    $VerificationVenv = Join-Path $TempRoot "verification-venv"
    Invoke-CheckedPython -Python $BackendPython -Arguments @("-m", "venv", $VerificationVenv)
    $VerificationPython = Join-Path $VerificationVenv "Scripts\python.exe"
    Invoke-CheckedPython -Python $VerificationPython -Arguments @("-m", "pip", "install", "pip==$PinnedPip")
    Invoke-CheckedPython -Python $VerificationPython -Arguments @("-m", "pip", "install", "-r", (Join-Path $ProjectRoot $ProductionLockRelative))
    Invoke-CheckedPython -Python $VerificationPython -Arguments @("-m", "pip", "check")
    Write-Host "Verified the production lock in a fresh temporary virtual environment." -ForegroundColor Green
  }
} finally {
  Remove-Item Env:CUSTOM_COMPILE_COMMAND -ErrorAction SilentlyContinue
  if (Test-Path -LiteralPath $TempRoot) {
    Remove-Item -LiteralPath $TempRoot -Recurse -Force
  }
}

if ((Get-FileHash -Algorithm SHA256 -LiteralPath $ProductionInput).Hash -ne $ProductionInputHash) {
  throw "Production dependency input changed during lock generation."
}
