$ErrorActionPreference = "Stop"
$PSNativeCommandUseErrorActionPreference = $true

$ProjectRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$Python = Join-Path $ProjectRoot "backend\.venv\Scripts\python.exe"
$RequirementsRelative = "backend\requirements.txt"
$LockRelative = "backend\requirements.lock.txt"
$LockFile = Join-Path $ProjectRoot $LockRelative
$PinnedPython = (Get-Content -Raw -LiteralPath (Join-Path $ProjectRoot ".python-version")).Trim()

if (-not (Test-Path -LiteralPath $Python -PathType Leaf)) {
  throw "Backend virtual environment not found: $Python"
}

$ActualPython = (& $Python -c "import platform; print(platform.python_version())").Trim()
if ($ActualPython -ne $PinnedPython) {
  throw "Lock generation requires Python $PinnedPython; found $ActualPython."
}

$PipToolsVersion = (& $Python -c "import importlib.metadata; print(importlib.metadata.version('pip-tools'))").Trim()
$env:CUSTOM_COMPILE_COMMAND = ".\scripts\compile_backend_lock.ps1"

Push-Location $ProjectRoot
try {
  & $Python -m piptools compile `
    $RequirementsRelative `
    --output-file $LockRelative `
    --generate-hashes `
    --strip-extras `
    --quiet
} finally {
  Pop-Location
}

$Content = Get-Content -Raw -Encoding UTF8 -LiteralPath $LockFile
$GeneratedHeader = '(?s)\A#\r?\n# This file is autogenerated by pip-compile with Python [^\r\n]+\r?\n# by the following command:\r?\n#\r?\n#\s+\.\\scripts\\compile_backend_lock\.ps1\r?\n#\r?\n'
$StableHeader = @"
#
# This file is autogenerated by pip-compile $PipToolsVersion with Python $ActualPython.
# Do not edit this file by hand.
# Regenerate it from the repository root with:
#
#    .\scripts\compile_backend_lock.ps1
#
"@
$StableHeader += [Environment]::NewLine
$Normalized = [Regex]::Replace($Content, $GeneratedHeader, $StableHeader, 1)
if ($Normalized -eq $Content) {
  throw "Unexpected pip-compile header; lock file was not normalized."
}
[IO.File]::WriteAllText($LockFile, $Normalized, [Text.UTF8Encoding]::new($false))

$Forbidden = Select-String -Path $LockFile -Pattern 'file:///|@ file:|[A-Za-z]:[\\/]|--index-url|--extra-index-url'
if ($Forbidden) {
  throw "Lock file contains a forbidden local path or package index."
}

$PackageCount = (Select-String -Path $LockFile -Pattern '^[A-Za-z0-9_.-]+==').Count
Write-Host "Generated $LockFile with $PackageCount pinned packages and hashes." -ForegroundColor Green
